db:
  host: 192.168.0.8
  port: 5432
  dbname: airlinersnet
  user: airlinersnet
  password: (3o2ob>pRNjE


organizer:
  tensorboard_root: /home/apollo/package/data/ssd/run/airlinersnet/tensorboard
  snapshot_root: /home/apollo/package/data/ssd/run/airlinersnet/snapshots


datasets:
  original:
    image_dir: /home/apollo/package/data/ssd/datasets/airlinersnet
    lmdb_dir: /home/apollo/package/data/ssd/run/airlinersnet/lmdb


logging:
  version: 1

  formatters:
    console_formatter:
      format: '[%(name)s] - %(message)s'

    file_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: WARNING
      stream: ext://sys.stdout

    root_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/root.out
      mode: w

    root_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/root.log
      maxBytes: 134217728
      backupCount: 8

    pipeline_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/pipeline.out
      mode: w

    pipeline_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/pipeline.log
      maxBytes: 134217728
      backupCount: 8

    wheel5_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/wheel5.out
      mode: w

    wheel5_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /home/apollo/package/data/ssd/run/airlinersnet/logs/wheel5.log
      maxBytes: 134217728
      backupCount: 8

  root:
    level: INFO
    handlers: [root_out_handler, root_log_handler, console_handler]

  loggers:
    pipeline.airliners:
      level: INFO
      handlers: [pipeline_out_handler, pipeline_log_handler, console_handler]

    wheel5:
      level: INFO
      handlers: [wheel5_out_handler, wheel5_log_handler, pipeline_out_handler, pipeline_log_handler, console_handler]

    wheel5.tracking:
      level: DEBUG
