tracking:
  snapshot_root: /data/ssd/run/airdetect/snapshots
  tensorboard_root: /data/ssd/run/airdetect/tensorboard
  tracker_root: /data/ssd/run/airdetect/tracker


datasets:
  train:
    image_dir: /data/ssd/datasets/airdetect250k/train
    metadata: /data/ssd/datasets/airdetect250k/train.csv
    lmdb_dir: /data/nvme/run/airdetect250k_C20/lmdb/train

  public_test:
    image_dir: /data/ssd/datasets/airdetect250k/public_test
    metadata: /data/ssd/datasets/airdetect250k/public_test.csv
    lmdb_dir: /data/nvme/run/airdetect250k_C20/lmdb/public_test

  private_test:
    image_dir: /data/ssd/datasets/airdetect250k/private_test
    metadata: /data/ssd/datasets/airdetect250k/private_test.csv
    lmdb_dir: /data/nvme/run/airdetect250k_C20/lmdb/private_test

  reallife:
    image_dir: /data/ssd/datasets/airdetect250k/reallife
    lmdb_dir: /data/nvme/run/airdetect250k_C20/lmdb/reallife

  debug:
    image_dir: /data/ssd/datasets/airdetect250k/debug

  classes: /data/ssd/datasets/airdetect250k/classes20


boost:
  heatmaps:
    train: /data/nvme/run/airdetect/boost/heatmaps/train


viz:
  nn_dir: /data/ssd/run/airdetect/viz/networks


logging:
  version: 1

  formatters:
    console_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: INFO
      stream: ext://sys.stderr

  root:
    level: INFO
    handlers: [console_handler]

  loggers:
    airdetect:
      level: INFO

    wheel5:
      level: INFO

    wheel5.dataset:
      level: INFO

    wheel5.metrics:
      level: INFO

    werkzeug:
      level: ERROR
