tracking:
  snapshot_root: /data/ssd/run/airdetect/snapshots
  tensorboard_root: /data/ssd/run/airdetect/tensorboard
  tracker_root: /data/ssd/run/airdetect/tracker


datasets:
  train:
    metadata: /data/ssd/datasets/airdetect/train.csv
    annotations: /data/ssd/datasets/airdetect/ext_train.csv
    image_dir: /data/ssd/datasets/airdetect/train
    lmdb_dir: /data/nvme/run/airdetect/lmdb/train

  public_test:
    metadata: /data/ssd/datasets/airdetect/public_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_public_test.csv
    image_dir: /data/ssd/datasets/airdetect/public_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/public_test

  private_test:
    metadata: /data/ssd/datasets/airdetect/private_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_private_test.csv
    image_dir: /data/ssd/datasets/airdetect/private_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/private_test

  classes: /data/ssd/datasets/airdetect/classes


boost:
  heatmaps:
    train: /data/nvme/run/airdetect/boost/heatmaps/train


viz:
  nn_dir: /data/ssd/run/airdetect/viz/networks


logging:
  version: 1

  formatters:
    console_formatter:
      format: '[%(name)s] - %(message)s'

    file_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: WARNING
      stream: ext://sys.stdout

    root_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/ssd/run/airdetect/logs/root.log
      maxBytes: 1073741824
      backupCount: 8

    airdetect_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/ssd/run/airdetect/logs/airdetect.log
      maxBytes: 1073741824
      backupCount: 8

    wheel5_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/ssd/run/airdetect/logs/wheel5.log
      maxBytes: 1073741824
      backupCount: 8

  root:
    level: INFO
    handlers: [root_handler, console_handler]

  loggers:
    airdetect:
      level: INFO
      handlers: [airdetect_handler, root_handler, console_handler]

    wheel5:
      level: INFO
      handlers: [wheel5_handler, root_handler, console_handler]

    wheel5.metrics:
      level: DEBUG

    werkzeug:
      level: WARNING
      handlers: [root_handler, console_handler]
