tracker:
  snapshot:
    root: /data/nvme/run/airliners/snapshots
  tensorboard:
    root: /data/nvme/run/airliners/tensorboard
    track_weights: 1


datasets:
  train:
    image_dir: /data/ssd/datasets/airliners/train
    dataframe: /data/ssd/datasets/airliners/train.csv
    lmdb_dir: /data/nvme/run/airliners/lmdb/train

  public_test:
    image_dir: /data/ssd/datasets/airliners/public_test
    dataframe: /data/ssd/datasets/airliners/public_test.csv
    lmdb_dir: /data/nvme/run/airliners/lmdb/public_test

  private_test:
    image_dir: /data/ssd/datasets/airliners/private_test
    dataframe: /data/ssd/datasets/airliners/private_test.csv
    lmdb_dir: /data/nvme/run/airliners/lmdb/private_test


viz:
  nn_dir: /data/nvme/run/airliners/viz/networks


logging:
  version: 1

  formatters:
    console_formatter:
      format: '[%(name)s] - %(message)s'

    file_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: WARNING
      stream: ext://sys.stdout

    root_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/nvme/run/airliners/logs/root.out
      mode: w

    root_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/nvme/run/airliners/logs/root.log
      maxBytes: 134217728
      backupCount: 8

    arena_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/nvme/run/airliners/logs/arena.out
      mode: w

    arena_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/nvme/run/airliners/logs/arena.log
      maxBytes: 134217728
      backupCount: 8

    wheel5_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/nvme/run/airliners/logs/wheel5.out
      mode: w

    wheel5_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/nvme/run/airliners/logs/wheel5.log
      maxBytes: 134217728
      backupCount: 8

  root:
    level: INFO
    handlers: [root_out_handler, root_log_handler, console_handler]

  loggers:
    arena:
      level: INFO
      handlers: [arena_out_handler, arena_log_handler, console_handler]

    wheel5:
      level: INFO
      handlers: [wheel5_out_handler, wheel5_log_handler, arena_out_handler, arena_log_handler, console_handler]

    wheel5.tracking:
      level: DEBUG
