tracking:
  snapshot_root: /data/ssd/run/airdetect/snapshots
  tensorboard_root: /data/ssd/run/airdetect/tensorboard
  tracker_root: /data/ssd/run/airdetect/tracker


datasets:
  train:
    metadata: /data/ssd/datasets/airdetect/train.csv
    annotations: /data/ssd/datasets/airdetect/ext_train.csv
    image_dir: /data/ssd/datasets/airdetect/train
    lmdb_dir: /data/nvme/run/airdetect/lmdb/train

  public_test:
    metadata: /data/ssd/datasets/airdetect/public_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_public_test.csv
    image_dir: /data/ssd/datasets/airdetect/public_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/public_test

  private_test:
    metadata: /data/ssd/datasets/airdetect/private_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_private_test.csv
    image_dir: /data/ssd/datasets/airdetect/private_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/private_test

  classes: /data/ssd/datasets/airdetect/classes


boost:
  heatmaps:
    train: /data/nvme/run/airdetect/boost/heatmaps/train


viz:
  nn_dir: /data/ssd/run/airdetect/viz/networks


logging:
  version: 1

  formatters:
    console_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: INFO
      stream: ext://sys.stderr

  root:
    level: INFO
    handlers: [console_handler]

  loggers:
    airdetect:
      level: INFO

    wheel5:
      level: INFO

    wheel5.dataset:
      level: INFO

    wheel5.metrics:
      level: INFO

    werkzeug:
      level: WARNING
