tracking:
  snapshot_root: /data/ssd/run/airdetect/snapshots
  tensorboard_root: /data/ssd/run/airdetect/tensorboard
  tracker_root: /data/ssd/run/airdetect/tracker

datasets:
  train:
    metadata: /data/ssd/datasets/airdetect/train.csv
    annotations: /data/ssd/datasets/airdetect/ext_train.csv
    image_dir: /data/ssd/datasets/airdetect/train
    lmdb_dir: /data/nvme/run/airdetect/lmdb/train

  public_test:
    metadata: /data/ssd/datasets/airdetect/public_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_public_test.csv
    image_dir: /data/ssd/datasets/airdetect/public_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/public_test

  private_test:
    metadata: /data/ssd/datasets/airdetect/private_test.csv
    annotations: /data/ssd/datasets/airdetect/ext_private_test.csv
    image_dir: /data/ssd/datasets/airdetect/private_test
    lmdb_dir: /data/nvme/run/airdetect/lmdb/private_test

  classes: /data/ssd/datasets/airdetect/classes


viz:
  nn_dir: /data/ssd/run/airdetect/viz/networks


logging:
  version: 1

  formatters:
    console_formatter:
      format: '[%(name)s] - %(message)s'

    file_formatter:
      format: '%(asctime)s %(levelname)-8s [%(name)s] - %(message)s'

  handlers:
    console_handler:
      class: logging.StreamHandler
      formatter: console_formatter
      level: WARNING
      stream: ext://sys.stdout

    root_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/ssd/run/airdetect/logs/root.out
      mode: w

    root_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/ssd/run/airdetect/logs/root.log
      maxBytes: 134217728
      backupCount: 8

    arena_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/ssd/run/airdetect/logs/arena.out
      mode: w

    arena_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: INFO
      filename: /data/ssd/run/airdetect/logs/arena.log
      maxBytes: 134217728
      backupCount: 8

    wheel5_out_handler:
      class: wheel5.logutils.BetterFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/ssd/run/airdetect/logs/wheel5.out
      mode: w

    wheel5_log_handler:
      class: wheel5.logutils.BetterRotatingFileHandler
      formatter: file_formatter
      level: DEBUG
      filename: /data/ssd/run/airdetect/logs/wheel5.log
      maxBytes: 134217728
      backupCount: 8

  root:
    level: INFO
    handlers: [root_out_handler, root_log_handler, console_handler]

  loggers:
    arena:
      level: INFO
      handlers: [arena_out_handler, arena_log_handler, console_handler]

    wheel5:
      level: INFO
      handlers: [wheel5_out_handler, wheel5_log_handler, arena_out_handler, arena_log_handler, console_handler]

    wheel5.tracking:
      level: DEBUG
